# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 770)
        icon = QtGui.QIcon.fromTheme(":/icons/qt-logo.png")
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setObjectName("layout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 20))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        self.menuImport = QtWidgets.QMenu(self.menuOpen)
        self.menuImport.setObjectName("menuImport")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtWidgets.QMenu(self.menuHelp)
        self.menuAbout.setObjectName("menuAbout")
        self.menuOther = QtWidgets.QMenu(self.menuHelp)
        self.menuOther.setObjectName("menuOther")
        self.menuSearch = QtWidgets.QMenu(self.menubar)
        self.menuSearch.setObjectName("menuSearch")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionCreate = QtWidgets.QAction(MainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionAboutQt = QtWidgets.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionAboutFluEdit = QtWidgets.QAction(MainWindow)
        self.actionAboutFluEdit.setObjectName("actionAboutFluEdit")
        self.actionLicense = QtWidgets.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.actionAboutPython = QtWidgets.QAction(MainWindow)
        self.actionAboutPython.setObjectName("actionAboutPython")
        self.actionAboutFluent = QtWidgets.QAction(MainWindow)
        self.actionAboutFluent.setObjectName("actionAboutFluent")
        self.actionFind_message_id = QtWidgets.QAction(MainWindow)
        self.actionFind_message_id.setObjectName("actionFind_message_id")
        self.actionFindNext = QtWidgets.QAction(MainWindow)
        self.actionFindNext.setObjectName("actionFindNext")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionFind_message = QtWidgets.QAction(MainWindow)
        self.actionFind_message.setObjectName("actionFind_message")
        self.actionIssues = QtWidgets.QAction(MainWindow)
        self.actionIssues.setObjectName("actionIssues")
        self.actionGithub = QtWidgets.QAction(MainWindow)
        self.actionGithub.setObjectName("actionGithub")
        self.actionGitlab = QtWidgets.QAction(MainWindow)
        self.actionGitlab.setObjectName("actionGitlab")
        self.actionReport_issue = QtWidgets.QAction(MainWindow)
        self.actionReport_issue.setObjectName("actionReport_issue")
        self.actionWiki = QtWidgets.QAction(MainWindow)
        self.actionWiki.setObjectName("actionWiki")
        self.actionDiscord = QtWidgets.QAction(MainWindow)
        self.actionDiscord.setObjectName("actionDiscord")
        self.actionGitter = QtWidgets.QAction(MainWindow)
        self.actionGitter.setObjectName("actionGitter")
        self.actionBuy_Me_A_Coffee = QtWidgets.QAction(MainWindow)
        self.actionBuy_Me_A_Coffee.setObjectName("actionBuy_Me_A_Coffee")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSave_all = QtWidgets.QAction(MainWindow)
        self.actionSave_all.setObjectName("actionSave_all")
        self.actionImportFTL = QtWidgets.QAction(MainWindow)
        self.actionImportFTL.setObjectName("actionImportFTL")
        self.actionImportSourceCode = QtWidgets.QAction(MainWindow)
        self.actionImportSourceCode.setObjectName("actionImportSourceCode")
        self.actionClose_all = QtWidgets.QAction(MainWindow)
        self.actionClose_all.setObjectName("actionClose_all")
        self.actionFind_in_memories = QtWidgets.QAction(MainWindow)
        self.actionFind_in_memories.setObjectName("actionFind_in_memories")
        self.menuImport.addAction(self.actionImportFTL)
        self.menuImport.addAction(self.actionImportSourceCode)
        self.menuOpen.addAction(self.actionOpen)
        self.menuOpen.addAction(self.actionCreate)
        self.menuOpen.addAction(self.actionSave)
        self.menuOpen.addAction(self.actionSave_as)
        self.menuOpen.addAction(self.actionSave_all)
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.menuImport.menuAction())
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.actionClose)
        self.menuOpen.addAction(self.actionClose_all)
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAboutQt)
        self.menuAbout.addAction(self.actionAboutFluEdit)
        self.menuAbout.addAction(self.actionAboutPython)
        self.menuAbout.addAction(self.actionAboutFluent)
        self.menuOther.addAction(self.actionIssues)
        self.menuOther.addAction(self.actionReport_issue)
        self.menuOther.addAction(self.actionGithub)
        self.menuOther.addAction(self.actionGitlab)
        self.menuOther.addAction(self.actionDiscord)
        self.menuOther.addAction(self.actionGitter)
        self.menuOther.addAction(self.actionBuy_Me_A_Coffee)
        self.menuHelp.addAction(self.menuAbout.menuAction())
        self.menuHelp.addAction(self.actionLicense)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionWiki)
        self.menuHelp.addAction(self.menuOther.menuAction())
        self.menuSearch.addAction(self.actionFind_message_id)
        self.menuSearch.addAction(self.actionFind_message)
        self.menuSearch.addAction(self.actionFindNext)
        self.menuSearch.addSeparator()
        self.menuSearch.addAction(self.actionFind_in_memories)
        self.menubar.addAction(self.menuOpen.menuAction())
        self.menubar.addAction(self.menuSearch.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionWiki.triggered.connect(MainWindow.notimplemented)
        self.actionAboutFluEdit.triggered.connect(MainWindow.notimplemented)
        self.actionAboutPython.triggered.connect(MainWindow.notimplemented)
        self.actionAboutFluent.triggered.connect(MainWindow.notimplemented)
        self.actionLicense.triggered.connect(MainWindow.show_license)
        self.actionGithub.triggered.connect(MainWindow.notimplemented)
        self.actionGitlab.triggered.connect(MainWindow.notimplemented)
        self.actionIssues.triggered.connect(MainWindow.notimplemented)
        self.actionReport_issue.triggered.connect(MainWindow.notimplemented)
        self.actionExit.triggered.connect(MainWindow.close)
        self.actionGitter.triggered.connect(MainWindow.notimplemented)
        self.actionDiscord.triggered.connect(MainWindow.notimplemented)
        self.actionBuy_Me_A_Coffee.triggered.connect(MainWindow.notimplemented)
        self.actionAboutQt.triggered.connect(MainWindow.on_about_qt)
        self.actionOpen.triggered.connect(MainWindow.on_open_file)
        self.actionCreate.triggered.connect(MainWindow.on_create_file)
        self.actionClose.triggered.connect(MainWindow.notimplemented)
        self.actionSave_all.triggered.connect(MainWindow.notimplemented)
        self.actionSave.triggered.connect(MainWindow.notimplemented)
        self.actionSave_as.triggered.connect(MainWindow.notimplemented)
        self.actionFind_message.triggered.connect(MainWindow.on_find_message)
        self.actionFindNext.triggered.connect(MainWindow.on_find_next)
        self.actionFind_message_id.triggered.connect(MainWindow.on_find_message_id)
        self.actionImportSourceCode.triggered.connect(MainWindow.notimplemented)
        self.actionImportFTL.triggered.connect(MainWindow.notimplemented)
        self.actionClose_all.triggered.connect(MainWindow.notimplemented)
        self.actionFind_in_memories.triggered.connect(MainWindow.notimplemented)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuOpen.setTitle(_translate("MainWindow", "File"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuOther.setTitle(_translate("MainWindow", "Other"))
        self.menuSearch.setTitle(_translate("MainWindow", "Search"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionCreate.setText(_translate("MainWindow", "Create"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionAboutQt.setText(_translate("MainWindow", "Qt"))
        self.actionAboutFluEdit.setText(_translate("MainWindow", "FluEdit"))
        self.actionLicense.setText(_translate("MainWindow", "License"))
        self.actionAboutPython.setText(_translate("MainWindow", "Python"))
        self.actionAboutFluent.setText(_translate("MainWindow", "Fluent"))
        self.actionFind_message_id.setText(_translate("MainWindow", "Find message by id"))
        self.actionFind_message_id.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionFindNext.setText(_translate("MainWindow", "Next"))
        self.actionFindNext.setShortcut(_translate("MainWindow", "F3"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionFind_message.setText(_translate("MainWindow", "Find message"))
        self.actionFind_message.setShortcut(_translate("MainWindow", "Ctrl+Shift+F"))
        self.actionIssues.setText(_translate("MainWindow", "Issues"))
        self.actionGithub.setText(_translate("MainWindow", "Github"))
        self.actionGitlab.setText(_translate("MainWindow", "Gitlab"))
        self.actionReport_issue.setText(_translate("MainWindow", "Report issue"))
        self.actionWiki.setText(_translate("MainWindow", "Wiki"))
        self.actionDiscord.setText(_translate("MainWindow", "Discord"))
        self.actionGitter.setText(_translate("MainWindow", "Gitter"))
        self.actionBuy_Me_A_Coffee.setText(_translate("MainWindow", "Buy Me A Coffee"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionSave_all.setText(_translate("MainWindow", "Save all"))
        self.actionImportFTL.setText(_translate("MainWindow", "From *.ftl"))
        self.actionImportSourceCode.setText(_translate("MainWindow", "From source code"))
        self.actionClose_all.setText(_translate("MainWindow", "Close all"))
        self.actionFind_in_memories.setText(_translate("MainWindow", "Find in memories"))


