# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/playground.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Playground(object):
    def setupUi(self, Playground):
        Playground.setObjectName("Playground")
        Playground.resize(739, 483)
        self.verticalLayout = QtWidgets.QVBoxLayout(Playground)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_4 = QtWidgets.QSplitter(Playground)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.translited_message_edit = QtWidgets.QTextEdit(self.layoutWidget)
        self.translited_message_edit.setObjectName("translited_message_edit")
        self.verticalLayout_5.addWidget(self.translited_message_edit)
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.textEdit_4 = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout_6.addWidget(self.textEdit_4)
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.textEdit_6 = QtWidgets.QTextEdit(self.layoutWidget_3)
        self.textEdit_6.setReadOnly(True)
        self.textEdit_6.setObjectName("textEdit_6")
        self.verticalLayout_8.addWidget(self.textEdit_6)
        self.layoutWidget_4 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.textEdit_5 = QtWidgets.QTextEdit(self.layoutWidget_4)
        self.textEdit_5.setReadOnly(True)
        self.textEdit_5.setObjectName("textEdit_5")
        self.verticalLayout_7.addWidget(self.textEdit_5)
        self.verticalLayout.addWidget(self.splitter_4)

        self.retranslateUi(Playground)
        QtCore.QMetaObject.connectSlotsByName(Playground)

    def retranslateUi(self, Playground):
        _translate = QtCore.QCoreApplication.translate
        Playground.setWindowTitle(_translate("Playground", "Form"))
        self.label_3.setText(_translate("Playground", "Translited message"))
        self.label_4.setText(_translate("Playground", "Config"))
        self.label.setText(_translate("Playground", "Language"))
        self.comboBox.setItemText(0, _translate("Playground", "en_US"))
        self.comboBox.setItemText(1, _translate("Playground", "en_UK"))
        self.comboBox.setItemText(2, _translate("Playground", "ru_RU"))
        self.label_2.setText(_translate("Playground", "Text Direction"))
        self.comboBox_2.setItemText(0, _translate("Playground", "Right-to-left"))
        self.comboBox_2.setItemText(1, _translate("Playground", "Left-to-right"))
        self.label_7.setText(_translate("Playground", "Variables"))
        self.label_5.setText(_translate("Playground", "Output"))
        self.label_6.setText(_translate("Playground", "Console"))


